server:
  servlet:
    context-path: /interview
  port: 3333
spring:
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 30
        max-wait: 30s
        max-idle: 30
        min-idle: 10